-- DDL


-- Crear la tabla B2B_CLASSIFICATION
CREATE TABLE B2B_CLASSIFICATION (
    ID NUMBER NOT NULL PRIMARY KEY,  -- Usar NUMBER para la clave primaria
    ID_PARENT NUMBER NOT NULL,  -- Usar NUMBER también para claves foráneas o referencias
    VALUE VARCHAR2(255),  -- Especificar tamaño para el campo VALUE
    DESCRIPTION VARCHAR2(500) NOT NULL  -- Especificar tamaño para DESCRIPTION
);

-- Comentarios para la tabla B2B_CLASSIFICATION
> COMMENT ON TABLE B2B_CLASSIFICATION IS 'Tabla que contiene la clasificación jerárquica de elementos.';

-- Comentarios para las columnas
> COMMENT ON COLUMN B2B_CLASSIFICATION.ID IS 'Identificador único de la clasificación.';
COMMENT ON COLUMN B2B_CLASSIFICATION.ID_PARENT IS 'Identificador de la clasificación padre (jerarquía).';
COMMENT ON COLUMN B2B_CLASSIFICATION.VALUE IS 'Valor asociado a la clasificación.';
COMMENT ON COLUMN B2B_CLASSIFICATION.DESCRIPTION IS 'Descripción de la clasificación.';

-- Crear el índice
> CREATE INDEX B2B_INDX_CLASS_1 ON B2B_CLASSIFICATION (ID_PARENT, VALUE);

-- ID_PARENT está relacionado con ID de la misma tabla, se añade clave foránea:
> ALTER TABLE B2B_CLASSIFICATION
ADD CONSTRAINT fk_b2b_classification_parent
FOREIGN KEY (ID_PARENT) REFERENCES B2B_CLASSIFICATION(ID);



-- DML
INSERT INTO CRM_APPLICATIONS
    (ID,NAME,CREATION_DATE,DESCRIPTION)
VALUES
    ('26','NUEVO POSPAGO B2B',SYSDATE,'NUEVO PRODUCTO EMPRESARIAL POSPAGO');

INSERT INTO CRM_PROPERTIES (
ID,
ID_DEVELOPER,
ID_ARCHITECT,
ID_APPLICATION,
NAME,
VALUE,
DESCRIPTION,
CREATION_DATE,
VERSION
) VALUES (
***** SEQUENCE_NAME *********,
1, -- ID_DEVELOPER
1, -- ID_ARCHITECT
26, -- ID_APPLICATION
'PLANES', -- NAME
'Postpago Empresarial=B2B_POSP_EMP', -- VALUE
'Planes Empresariales', -- DESCRIPTION
SYSDATE, -- CREATION_DATE
'1' -- VERSION
);

INSERT INTO CRM_PROPERTIES (
ID,
ID_DEVELOPER,
ID_ARCHITECT,
ID_APPLICATION,
NAME,
VALUE,
DESCRIPTION,
CREATION_DATE,
VERSION
) VALUES (
***** SEQUENCE_NAME *********,
1, -- ID_DEVELOPER
1, -- ID_ARCHITECT
26, -- ID_APPLICATION
'LINEAS_MAXIMAS', -- NAME
'20', -- VALUE
'TOTAL MAXIMO DE LINEAS A MOSTRAR', -- DESCRIPTION
SYSDATE, -- CREATION_DATE
'1' -- VERSION
);

INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (1, NULL, 'TIPOS CONTRATO', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (2, 1, 'ESTANDAR', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (3, 1, 'NEGOCIADO', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (4, NULL, 'PLANES', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (5, 4, 'POSTPAGO EMPRESARIAL', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (6, NULL, 'LINEA PRODUCTO', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (7, 6, 'ESTÁNDAR', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (8, 6, 'AVANZADO', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (9, NULL, 'TIPO FAMILIA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (10, 9, 'MÓVIL', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (11, 9, 'IOT', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (12, NULL, 'TIPO PRODUCTO', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (13, 11, 'NUEVO PRODUCTO POSTPAGO', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (14, NULL, 'TIPOS ENVIO', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (15, 13, 'OPERADOR LOGÍSTICO', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (16, 13, 'ENTREGA POR COMERCIAL', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (17, NULL, 'GRUPOS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (18, 17, 'GRUPO 1', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (19, 17, 'GRUPO 2', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (20, 17, 'GRUPO 3', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (21, 17, 'GRUPO 4', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (22, 17, 'ADMINITRACION', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (23, 17, 'ADMINITRADORES DE VENTAS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (24, 17, 'ANALISTAS DE VENTAS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (25, 17, 'ASESORES', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (26, 17, 'ASESORES COMERCIALES', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (27, 17, 'AUDITORIA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (28, 17, 'COMPRAS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (29, 17, 'CONTAC CENTER', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (30, 17, 'COORDINADORES', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (31, 17, 'COORDINADORES DE VENTAS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (32, 17, 'DIRECTORES', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (33, 17, 'DIRECTORES DE VENTAS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (34, 17, 'EJECUTIVOS DE VENTAS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (35, 17, 'FINANZAS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (36, 17, 'GERENTES', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (37, 17, 'INFORMATICA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (38, 17, 'LIDERES', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (39, 17, 'LOGISTICA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (40, 17, 'MARKETING', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (41, 17, 'MENSAJEROS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (42, 17, 'MERCADEO', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (43, 17, 'OPERACIONES', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (44, 17, 'OPERARIOS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (45, 17, 'PRESIDENCIA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (46, 17, 'PRODUCCIÓN', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (47, 17, 'PUNTOS DE VENTA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (48, 17, 'RECEPCION', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (49, 17, 'RECURSOS HUMANOS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (50, 17, 'SECRETARIA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (51, 17, 'SERVICIOS AL CLIENTE', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (52, 17, 'SUBGERENTES VENTAS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (53, 17, 'TECNOLOGIA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (54, 17, 'TESORERIA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (55, 17, 'VENTAS', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (56, 17, 'VICEPRESIDENTES', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (57, NULL, 'ESTADOS DE LINEA', NULL);
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (58, 57, 'PENDIENTE', 'La configuración de la oferta se encuentra en proceso de registro');
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (59, 57, 'EN EJECUCIÓN', 'Se envió la oferta completa al proceso de aprovisionamiento y aún se encuentran líneas pendientes por activar.');
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (60, 57, 'PROCESADA', 'Cuando todas las líneas de la oferta se encuentran activas.');
INSERT INTO B2B_CLASSIFICATION (ID, ID_PARENT, VALUE, DESCRIPTION) VALUES (61, 57, 'FALLIDO', 'Se muestra este




